projects:
  sneak:
    schemaPath: graphql/schema.json
    includes:
      - S
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: graphql
