/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_appsync_graphqlEndpoint": "https://zbrtwynzpvcozezgaxae6onyyi.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-hzh4iokuivhdfcr4j2tkrfx3a4",
    "aws_cognito_identity_pool_id": "ap-southeast-2:690a6750-a16a-4742-bb83-4e035690d546",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_AzqGadnQ3",
    "aws_user_pools_web_client_id": "453lhgtlv5o096neqjbo8pjnud",
    "oauth": {},
    "aws_user_files_s3_bucket": "sneak23ccd061d7d945cea35d01da10d57ee3125055-dev",
    "aws_user_files_s3_bucket_region": "ap-southeast-2"
};


export default awsmobile;
